app = "soundbridge-ollama"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 11434
  protocol = "tcp"

     [[services.ports]]
     port = 80
     handlers = ["http"]
     force_https = true

     [[services.ports]]
     port = 443
     handlers = ["tls", "http"]

[vm]
  memory = "4gb"
  cpus = 2
  cpu_kind = "performance"

[machine]
  auto_stop_machines = false
  auto_start_machines = true